### ISSUE TITLE
readme should outline what the code will do

### ISSUE THREAD

**Issue by iancrowther** [gitevents/gitevents-cli#2]
see https://github.com/gitevents/core/issues/100

**Comment by iancrowther** [comment]
@nnevala is this complete?

is it worth creating a demo video?

**Comment by nnevala** [comment]
I don't think there's any point in putting effort towards a video when the entire tool has just started to take shape. Readme should be improved as an on going process, happy for anyone to to chip in there.

**Comment by iancrowther** [comment]
👍
